# Generated by Django 5.2.4 on 2025-07-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0002_solicitacao_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='embarcado',
            field=models.BooleanField(default=False),
        ),
    ]
