# Generated by Django 5.2.4 on 2025-07-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0003_material_embarcado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='andamento', max_length=20),
        ),
    ]
