# Generated by Django 5.2.4 on 2025-07-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0004_solicitacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='embarcacao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='supervisor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
