# Generated by Django 5.2.4 on 2025-07-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0006_solicitacao_concluida_solicitacao_retornado_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='cpf',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
